name: Deploy to o2switch

on:
  push:
    branches:
      - main  # ou votre branche de production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'  # ajustez selon votre version de Node.js

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build
        run: cd frontend && npm run build  # ou votre commande pour construire le projet

      - name: List build directory
        run: ls -la ./frontend/dist  # Vérifiez le contenu du répertoire de build

      - name: Deploy to o2switch
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: 109.234.166.213
          username: luza5303
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: ./frontend/dist
          remote_dir: ./food-order.lestudio4k.com
