name: Deploy to o2switch

on:
  push:
    branches:
      - main  # ou votre branche de production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'  # ajustez selon votre version de Node.js

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Install react-icons
        run: npm install react-icons
        working-directory: ./frontend

      - name: install recharts
        run:  npm install recharts
        working-directory: ./frontend

      - name: react-router fix
        run: npm install react-router-dom@6
        working-directory: ./frontend

      - name: Verify the correct package.json is used
        run: cat ./frontend/package.json

      - name: Build
        run: npm run build  # ou votre commande pour construire le projet
        working-directory: ./frontend

      - name: Deploy to o2switch
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: 109.234.166.213
          username: luza5303
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: ./frontend/dist
          remote_dir: ./food-order.lestudio4k.com
